// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgerXOA8C9qtjB1yP3oAbsvMAjpFHPSmc',
    appId: '1:129949648924:web:a4dbfa27af569b478337d9',
    messagingSenderId: '129949648924',
    projectId: 'jpstudy-v2',
    authDomain: 'jpstudy-v2.firebaseapp.com',
    storageBucket: 'jpstudy-v2.firebasestorage.app',
    measurementId: 'G-PKT7ELMCHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6LJy0gk8pDgH3BMHi5MlRH8_GSADEatA',
    appId: '1:129949648924:android:4e2023b729a0cb3e8337d9',
    messagingSenderId: '129949648924',
    projectId: 'jpstudy-v2',
    storageBucket: 'jpstudy-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDQotl8CQ5BNmjqv-eXpTTKQAoQ0wUukM',
    appId: '1:129949648924:ios:ad22cf784be09a1c8337d9',
    messagingSenderId: '129949648924',
    projectId: 'jpstudy-v2',
    storageBucket: 'jpstudy-v2.firebasestorage.app',
    iosClientId:
        '129949648924-efhe0b51c56i79772kb1pivq94ogouk6.apps.googleusercontent.com',
    iosBundleId: 'com.jpstudy.jpstudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgerXOA8C9qtjB1yP3oAbsvMAjpFHPSmc',
    appId: '1:129949648924:web:0b2d415594a5bf5f8337d9',
    messagingSenderId: '129949648924',
    projectId: 'jpstudy-v2',
    authDomain: 'jpstudy-v2.firebaseapp.com',
    storageBucket: 'jpstudy-v2.firebasestorage.app',
    measurementId: 'G-G60JCZHXX7',
  );
}
