#!/usr/bin/env python3
"""Audit and standardize grammar example coverage for N5-N3."""

from __future__ import annotations

import argparse
import json
import re
import sys
import unicodedata
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GRAMMAR_ROOT = ROOT / 'assets' / 'data' / 'content' / 'grammar'
EXAMPLE_ROOT = ROOT / 'assets' / 'data' / 'content' / 'grammar_examples'
REPORT_JSON = ROOT / 'docs' / 'reports' / 'grammar-example-coverage-report.json'
REPORT_MD = ROOT / 'docs' / 'reports' / 'grammar-example-expansion-plan.md'
LEVELS = ('n5', 'n4', 'n3')
TARGET_MIN_EXAMPLES = 10


@dataclass(frozen=True)
class Definition:
    lesson: int
    title: str
    grammar_point: str | None


def _read_json(path: Path):
    return json.loads(path.read_text(encoding='utf-8-sig'))


def _write_json(path: Path, payload) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + '\n',
        encoding='utf-8',
    )


def _normalize_waves(text: str) -> str:
    return text.replace('～', '〜').replace('~', '〜')


def _normalize_label(text: str | None) -> str:
    if text is None:
        return ''
    return unicodedata.normalize('NFKC', _normalize_waves(str(text))).strip()


def _compact_label(text: str) -> str:
    normalized = _normalize_label(text)
    normalized = normalized.lower()
    normalized = re.sub(r'[\s\u3000\(\)（）\[\]【】「」『』:：,，.．/／・\-\+]+', '', normalized)
    return normalized.strip()


def _extract_japanese_core(text: str) -> str:
    normalized = _normalize_label(text)
    return ''.join(re.findall(r'[〜ぁ-ゖァ-ヶ一-龯々ー]', normalized)).strip()


def _relax_optional_no(text: str) -> str:
    return re.sub(r'^〜の(?=ために)', '〜', text, count=1)


def _definition_labels(definition: Definition) -> list[str]:
    return [definition.title, definition.grammar_point or '']


def _match_definition(
    definitions: list[Definition],
    example_label: str,
) -> Definition | None:
    normalized_example = _normalize_label(example_label)
    if not normalized_example:
        return None

    compact_example = _compact_label(normalized_example)
    relaxed_compact_example = _compact_label(_relax_optional_no(normalized_example))
    japanese_core_example = _extract_japanese_core(normalized_example)
    relaxed_japanese_core_example = _relax_optional_no(japanese_core_example)

    # 1. Exact normalized string match.
    for definition in definitions:
        for label in _definition_labels(definition):
            if _normalize_label(label) == normalized_example:
                return definition

    # 2. Exact compact full-string match.
    for definition in definitions:
        for label in _definition_labels(definition):
            if _compact_label(label) == compact_example:
                return definition

    # 3. Limited optional-の normalization for known safe patterns like `〜のために`.
    for definition in definitions:
        for label in _definition_labels(definition):
            if _compact_label(_relax_optional_no(_normalize_label(label))) == relaxed_compact_example:
                return definition

    # 4. Japanese-core fallback only when it identifies exactly one definition.
    if not japanese_core_example:
        return None

    japanese_core_matches: list[Definition] = []
    for definition in definitions:
        for label in _definition_labels(definition):
            normalized_label = _normalize_label(label)
            label_core = _extract_japanese_core(normalized_label)
            relaxed_label_core = _relax_optional_no(label_core)
            if label_core == japanese_core_example or relaxed_label_core == relaxed_japanese_core_example:
                japanese_core_matches.append(definition)
                break

    unique_matches = {
        (item.lesson, item.title, item.grammar_point): item
        for item in japanese_core_matches
    }
    if len(unique_matches) == 1:
        return next(iter(unique_matches.values()))

    return None


def _lesson_files(level: str) -> list[tuple[Path, Path, int]]:
    grammar_dir = GRAMMAR_ROOT / level
    example_dir = EXAMPLE_ROOT / level
    result = []
    for grammar_path in sorted(grammar_dir.glob(f'grammar_{level}_*.json')):
        lesson = int(grammar_path.stem.rsplit('_', 1)[-1])
        result.append((grammar_path, example_dir / f'lesson_{lesson}.json', lesson))
    return result


def _render_markdown(report: dict) -> str:
    lines = [
        '# Grammar Example Expansion Plan',
        '',
        'This report is generated by `tooling/audit_grammar_example_coverage.py`.',
        '',
        '## Coverage Summary',
        '',
        '| Level | Points | Example Blocks | Total Examples | Avg / Point | Below 10 | Missing To 10 |',
        '| --- | ---: | ---: | ---: | ---: | ---: | ---: |',
    ]
    for level in report['summaryByLevel']:
        lines.append(
            f"| {level['level']} | {level['grammarPoints']} | {level['exampleBlocks']} | "
            f"{level['totalExamples']} | {level['averageExamplesPerPoint']:.2f} | "
            f"{level['belowTargetCount']} | {level['missingToTarget']} |"
        )

    lines.extend(
        [
            '',
            '## Batch Plan',
            '',
            '1. `Pass A` - Canonicalize `grammar_examples[*].grammarPoint` to match the lesson definition title exactly.',
            '2. `Pass B` - Fill `N5` grammar points to at least 10 examples.',
            '3. `Pass C` - Fill `N4` grammar points to at least 10 examples.',
            '4. `Pass D` - Fill `N3` grammar points to at least 10 examples.',
            '',
            '## Current Low-Coverage Queue',
            '',
            '| Level | Lesson | Grammar Point | Current | Missing |',
            '| --- | ---: | --- | ---: | ---: |',
        ]
    )

    for item in report['lowCoverage']:
        lines.append(
            f"| {item['level']} | {item['lesson']} | {item['grammarPoint']} | "
            f"{item['exampleCount']} | {item['missingToTarget']} |"
        )

    if report['renamedExampleBlocks']:
        lines.extend(
            [
                '',
                '## Canonical Label Renames',
                '',
                '| File | From | To |',
                '| --- | --- | --- |',
            ]
        )
        for item in report['renamedExampleBlocks']:
            lines.append(
                f"| {item['file']} | {item['from']} | {item['to']} |"
            )

    return '\n'.join(lines) + '\n'


def main() -> int:
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8')

    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--apply',
        action='store_true',
        help='Rewrite grammar_examples files with canonical grammarPoint labels.',
    )
    args = parser.parse_args()

    renamed_example_blocks: list[dict[str, str]] = []
    unmatched_example_blocks: list[dict[str, str | int]] = []
    low_coverage: list[dict[str, str | int]] = []
    summary_by_level: list[dict[str, int | float | str]] = []

    for level in LEVELS:
        level_points = 0
        level_blocks = 0
        level_examples = 0
        level_below_target = 0
        level_missing_to_target = 0

        for grammar_path, example_path, lesson in _lesson_files(level):
            definitions_raw = _read_json(grammar_path)
            examples_raw = _read_json(example_path)

            definitions = [
                Definition(
                    lesson=lesson,
                    title=str(item.get('title', '')).strip(),
                    grammar_point=str(item.get('grammarPoint', '')).strip() or None,
                )
                for item in definitions_raw
            ]

            block_by_title: dict[str, dict] = {}
            normalized_blocks: list[dict] = []
            changed = False

            for block in examples_raw:
                old_label = str(block.get('grammarPoint', '')).strip()
                matched = _match_definition(definitions, old_label)
                if matched is None:
                    unmatched_example_blocks.append(
                        {
                            'level': level.upper(),
                            'lesson': lesson,
                            'grammarPoint': old_label,
                            'file': str(example_path.relative_to(ROOT)).replace('\\', '/'),
                        }
                    )
                    normalized_blocks.append(block)
                    if old_label:
                        block_by_title[old_label] = block
                    continue

                canonical_label = matched.title
                if old_label != canonical_label:
                    block['grammarPoint'] = canonical_label
                    renamed_example_blocks.append(
                        {
                            'file': str(example_path.relative_to(ROOT)).replace('\\', '/'),
                            'from': old_label,
                            'to': canonical_label,
                        }
                    )
                    changed = True

                normalized_blocks.append(block)
                block_by_title[canonical_label] = block

            ordered_blocks: list[dict] = []
            seen_titles: set[str] = set()
            for definition in definitions:
                block = block_by_title.get(definition.title)
                if block is None:
                    block = {'grammarPoint': definition.title, 'examples': []}
                    changed = True
                ordered_blocks.append(block)
                seen_titles.add(definition.title)

            leftovers = [
                block for block in normalized_blocks
                if str(block.get('grammarPoint', '')).strip() not in seen_titles
            ]
            if leftovers:
                ordered_blocks.extend(leftovers)

            if args.apply and (changed or ordered_blocks != examples_raw):
                _write_json(example_path, ordered_blocks)

            level_points += len(definitions)
            level_blocks += len(ordered_blocks)
            level_examples += sum(len(block.get('examples', [])) for block in ordered_blocks)

            for definition in definitions:
                block = next(
                    (
                        item
                        for item in ordered_blocks
                        if str(item.get('grammarPoint', '')).strip() == definition.title
                    ),
                    None,
                )
                example_count = len(block.get('examples', [])) if block else 0
                if example_count < TARGET_MIN_EXAMPLES:
                    level_below_target += 1
                    missing_to_target = TARGET_MIN_EXAMPLES - example_count
                    level_missing_to_target += missing_to_target
                    low_coverage.append(
                        {
                            'level': level.upper(),
                            'lesson': lesson,
                            'grammarPoint': definition.title,
                            'exampleCount': example_count,
                            'missingToTarget': missing_to_target,
                            'file': str(example_path.relative_to(ROOT)).replace('\\', '/'),
                        }
                    )

        summary_by_level.append(
            {
                'level': level.upper(),
                'grammarPoints': level_points,
                'exampleBlocks': level_blocks,
                'totalExamples': level_examples,
                'averageExamplesPerPoint': round(level_examples / level_points, 2),
                'belowTargetCount': level_below_target,
                'missingToTarget': level_missing_to_target,
            }
        )

    low_coverage.sort(key=lambda item: (item['level'], item['lesson'], item['grammarPoint']))
    renamed_example_blocks.sort(key=lambda item: (item['file'], item['to']))

    batch_counter = Counter(item['level'] for item in low_coverage)
    missing_counter = defaultdict(int)
    for item in low_coverage:
        missing_counter[item['level']] += int(item['missingToTarget'])

    report = {
        'targetMinimumExamples': TARGET_MIN_EXAMPLES,
        'summaryByLevel': summary_by_level,
        'batchSummary': [
            {
                'batch': 'Pass A',
                'scope': 'Canonicalize grammarPoint labels in grammar_examples',
                'renamedBlocks': len(renamed_example_blocks),
                'unmatchedBlocks': len(unmatched_example_blocks),
            },
            {
                'batch': 'Pass B',
                'scope': 'Fill N5 grammar points to 10 examples',
                'pointsBelowTarget': batch_counter['N5'],
                'missingExamples': missing_counter['N5'],
            },
            {
                'batch': 'Pass C',
                'scope': 'Fill N4 grammar points to 10 examples',
                'pointsBelowTarget': batch_counter['N4'],
                'missingExamples': missing_counter['N4'],
            },
            {
                'batch': 'Pass D',
                'scope': 'Fill N3 grammar points to 10 examples',
                'pointsBelowTarget': batch_counter['N3'],
                'missingExamples': missing_counter['N3'],
            },
        ],
        'renamedExampleBlocks': renamed_example_blocks,
        'unmatchedExampleBlocks': unmatched_example_blocks,
        'lowCoverage': low_coverage,
    }

    _write_json(REPORT_JSON, report)
    REPORT_MD.write_text(_render_markdown(report), encoding='utf-8')
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
